import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native"
var height = Dimensions.get('window').height;
var width = Dimensions.get('window').width;
export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'stretch',
    justifyContent: 'center',
    height: height,
    //marginTop: StatusBar.currentHeight || 0,
  },
  profileBoxTop: {
    backgroundColor: '#fff',
    marginHorizontal: 10,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 3,
    marginTop: Platform.OS === 'ios' ? '1%' : '3%',
  },
  textInput: {
    width: '100%',
    marginTop: '15%',
    marginBottom: 1,
    borderColor: '#000080',
    borderBottomWidth: 1,
    fontSize: 15,
  },
  button: {
    width: '80%',
    //width: (width - 20) / 3,
    height: 40,
    paddingHorizontal: 5,
    marginRight: 10,
    borderRadius: 5,
    borderWidth: 0.6,
    backgroundColor: '#d9dbd9',
    shadowColor: '#666',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 3,
    borderColor: '#9f9f9f',
  },
  buttonText: {
    fontSize: 14,
    textAlign: 'center',
    paddingTop: 8,
    fontWeight: 'bold'
  },
  loading: {
    flex: 1,
    //position: 'absolute',
    left: 0,
    right: 0,
    top: '5%',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  activityIndicatorWrapper: {
    backgroundColor: '#FFFFFF',
    height: 100,
    width: 100,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  profileBoxBottom: {
    flex: 1,
    backgroundColor: '#fff',
    marginHorizontal: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 3,
    marginTop: Platform.OS === 'ios' ? '1%' : '10%',
  },
  scrollboxActionContainer: {
    backgroundColor: '#fff',
    marginHorizontal: 10,
    justifyContent: 'center',
    marginTop: Platform.OS === 'ios' ? '5%' : '10%',
  },
  scrollboxActionContainerInner: {
    height: 34,
    backgroundColor: '#fff'
  },
  scrollboxHorizontal: {
    flex: 2,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 3,
    backgroundColor: '#808080',
  },
  scrollboxActionText: {
    color: '#fff',
    borderRightColor: '#000',
    fontWeight: 'bold',
    padding: 8,
    borderRightWidth: 1,
    borderColor: '#fff',
    backgroundColor: '#808080',
    fontSize: 13,
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  arrowicon: {
  },
  tabActiveText: {
    backgroundColor: '#007bff',
  },
  scrollboxActionFirst: {
    color: '#fff',
    fontSize: 13,
    borderRightColor: '#000',
    fontWeight: 'bold',
    padding: 8,
    borderRightWidth: 1,
    borderColor: '#fff',
    borderRadius: 10,
  },
})